# Generated by Django 3.2.3 on 2021-09-03 06:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SpotOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('symbol', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('side', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('average', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('amount_in_quote', models.FloatField(blank=True, null=True)),
                ('filled', models.FloatField(blank=True, null=True)),
                ('remaining', models.FloatField(blank=True, null=True)),
                ('pure_amount', models.FloatField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('fee', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SpotSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('step_share_set_mode', models.CharField(max_length=50)),
                ('target_share_set_mode', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpotTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_price', models.FloatField()),
                ('share', models.FloatField(blank=True, null=True)),
                ('is_triggered', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0)),
                ('released_amount_in_quote', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('operation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target', to='spot_trader.spotoperation')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='spot_trader.spotsignal')),
            ],
        ),
        migrations.CreateModel(
            name='SpotStoploss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_price', models.FloatField()),
                ('is_triggered', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0)),
                ('released_amount_in_quote', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('operation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stoploss', to='spot_trader.spotoperation')),
            ],
        ),
        migrations.CreateModel(
            name='SpotStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.FloatField()),
                ('share', models.FloatField(blank=True, null=True)),
                ('is_triggered', models.BooleanField(default=False)),
                ('amount_in_quote', models.FloatField(blank=True, null=True)),
                ('purchased_amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('operation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step', to='spot_trader.spotoperation')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='spot_trader.spotsignal')),
            ],
        ),
        migrations.AddField(
            model_name='spotsignal',
            name='stoploss',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal', to='spot_trader.spotstoploss'),
        ),
        migrations.CreateModel(
            name='SpotPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField()),
                ('keep_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='spot_trader.spotsignal')),
            ],
        ),
        migrations.AddField(
            model_name='spotoperation',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='operation', to='spot_trader.spotorder'),
        ),
        migrations.AddField(
            model_name='spotoperation',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='spot_trader.spotposition'),
        ),
        migrations.CreateModel(
            name='SpotBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_id', models.CharField(max_length=100)),
                ('credential_id', models.CharField(max_length=100)),
                ('strategy', models.CharField(max_length=100)),
                ('total_pnl', models.FloatField(default=0)),
                ('total_pnl_percentage', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(default='running', max_length=50)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='spot_trader.spotposition')),
            ],
        ),
    ]
