# Generated by Django 3.2.7 on 2021-09-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_trader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotposition',
            old_name='size',
            new_name='amount_in_quote',
        ),
        migrations.RemoveField(
            model_name='spotstoploss',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='spotstoploss',
            name='released_amount_in_quote',
        ),
        migrations.AddField(
            model_name='spotposition',
            name='purchased_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='spotposition',
            name='released_amount_in_quote',
            field=models.FloatField(default=0),
        ),
    ]
