# Generated by Django 3.2.7 on 2021-09-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot_trader', '0003_rename_amount_spottarget_purchased_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotbot',
            old_name='total_pnl',
            new_name='final_pnl',
        ),
        migrations.RenameField(
            model_name='spotbot',
            old_name='total_pnl_percentage',
            new_name='final_pnl_percentage',
        ),
    ]
