# Generated by Django 3.2.7 on 2021-09-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot_trader', '0004_auto_20210912_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotbot',
            old_name='final_pnl',
            new_name='total_pnl',
        ),
        migrations.RenameField(
            model_name='spotbot',
            old_name='final_pnl_percentage',
            new_name='total_pnl_percentage',
        ),
    ]
