# Generated by Django 3.2.7 on 2021-09-15 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot_trader', '0006_auto_20210915_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotorder',
            name='filled',
        ),
        migrations.RemoveField(
            model_name='spotorder',
            name='remaining',
        ),
    ]
