# Generated by Django 3.2.7 on 2021-09-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot_trader', '0007_auto_20210915_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotorder',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='spotorder',
            name='fee',
        ),
    ]
