# Generated by Django 3.2.7 on 2021-09-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_trader', '0008_auto_20210915_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='spottarget',
            name='type',
            field=models.CharField(default='tp', max_length=20),
            preserve_default=False,
        ),
    ]
