# Generated by Django 3.2.7 on 2021-09-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_trader', '0009_spottarget_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spottarget',
            name='type',
            field=models.CharField(choices=[('tp', 'Tp'), ('trail', 'Trail'), ('trail_and_tp', 'Trail And Tp')], max_length=20),
        ),
    ]
