# Generated by Django 3.2.7 on 2021-09-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_trader', '0011_auto_20210923_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spottarget',
            name='share',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
