# Generated by Django 3.2.7 on 2021-09-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot_trader', '0013_remove_spottarget_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotsignal',
            old_name='step_share_set_mode',
            new_name='setup_mode',
        ),
    ]
