# Generated by Django 3.2.3 on 2021-05-26 20:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('steps', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('targets', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('stop_loss', models.FloatField()),
            ],
        ),
    ]
