# Generated by Django 3.2.3 on 2021-06-19 19:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('exchange_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('symbol', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('side', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('average', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('filled', models.FloatField(blank=True, null=True)),
                ('remaining', models.FloatField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('fee', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpotSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_id', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=50)),
                ('steps', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('targets', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('stop_loss', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SpotPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.CharField(max_length=100, unique=True)),
                ('volume', models.FloatField()),
                ('strategy', models.CharField(max_length=100)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='positions', to='trader.spotsignal')),
            ],
            managers=[
                ('objcets', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpotBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.CharField(max_length=100, unique=True)),
                ('exchange_id', models.CharField(max_length=100)),
                ('credential_id', models.CharField(max_length=100)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='bot', to='trader.spotposition')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField(max_length=100, unique=True)),
                ('action', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='operation', to='trader.spotorder')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='operations', to='trader.spotposition')),
            ],
        ),
    ]
