# Generated by Django 3.2.3 on 2021-06-30 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotposition',
            name='signal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='positions', to='trader.spotsignal'),
        ),
    ]
