# Generated by Django 3.2.3 on 2021-07-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotorder',
            name='order_id',
        ),
        migrations.AddField(
            model_name='spotorder',
            name='amount_in_quote',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotorder',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
