# Generated by Django 3.2.3 on 2021-05-27 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotOrder',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('timestamp', models.BigIntegerField()),
                ('status', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('side', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('average', models.FloatField()),
                ('amount', models.FloatField()),
                ('filled', models.FloatField()),
                ('remaining', models.FloatField()),
                ('cost', models.FloatField()),
                ('fee', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SpotStrategy',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SpotPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='trader.spotsignal')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='position', to='trader.spotstrategy')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('is_done', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='operation', to='trader.spotorder')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='operations', to='trader.spotposition')),
            ],
        ),
    ]
