# Generated by Django 3.2.3 on 2021-08-09 15:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_auto_20210720_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotsignal',
            name='stoploss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotsignal',
            name='targets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
