# Generated by Django 3.2.3 on 2021-08-09 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_auto_20210809_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='trader.spotposition'),
        ),
        migrations.AlterField(
            model_name='spotbot',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='trader.spotposition'),
        ),
        migrations.AlterField(
            model_name='spotposition',
            name='signal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='trader.spotsignal'),
        ),
    ]
