# Generated by Django 3.2.3 on 2021-08-10 13:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_auto_20210809_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotsignal',
            name='step_weights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='spotsignal',
            name='target_weights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
