# Generated by Django 3.2.3 on 2021-06-30 12:34

import datetime
from django.db import migrations
import trader.main.spot.models.position


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_alter_spotposition_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotposition',
            name='created_at',
            field=trader.main.spot.models.position.TimeFieldTZ(blank=True, default=datetime.datetime.now),
        ),
    ]
