# Generated by Django 3.2.3 on 2021-08-10 13:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0005_auto_20210810_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotsignal',
            name='step_weights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
