# Generated by Django 3.2.3 on 2021-06-30 12:43

import datetime
from django.db import migrations
import trader.main.spot.models.utils.time_filed_tz


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0005_alter_spotposition_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='created_at',
            field=trader.main.spot.models.utils.time_filed_tz.TimeFieldTZ(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='operation',
            name='executed_at',
            field=trader.main.spot.models.utils.time_filed_tz.TimeFieldTZ(blank=True),
        ),
        migrations.AlterField(
            model_name='spotbot',
            name='created_at',
            field=trader.main.spot.models.utils.time_filed_tz.TimeFieldTZ(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='spotorder',
            name='created_at',
            field=trader.main.spot.models.utils.time_filed_tz.TimeFieldTZ(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='spotsignal',
            name='created_at',
            field=trader.main.spot.models.utils.time_filed_tz.TimeFieldTZ(blank=True, default=datetime.datetime.now),
        ),
    ]
