# Generated by Django 3.2.3 on 2021-06-30 12:51

from django.db import migrations
import django.utils.timezone
import trader.main.spot.models.utils.time_filed_tz


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0006_auto_20210630_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotposition',
            name='created_at',
            field=trader.main.spot.models.utils.time_filed_tz.TimeFieldTZ(blank=True, default=django.utils.timezone.now),
        ),
    ]
