# Generated by Django 3.2.3 on 2021-06-30 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0007_alter_spotposition_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotposition',
            name='created_at',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
        ),
    ]
