# Generated by Django 3.2.3 on 2021-08-11 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0008_auto_20210810_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotsignal',
            name='step_shares',
        ),
        migrations.RemoveField(
            model_name='spotsignal',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='spotsignal',
            name='target_shares',
        ),
        migrations.RemoveField(
            model_name='spotsignal',
            name='targets',
        ),
        migrations.AlterField(
            model_name='operation',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='spotbot',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='spotorder',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='spotposition',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='spotsignal',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
