# Generated by Django 3.2.3 on 2021-08-11 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0009_auto_20210811_1556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operation',
            new_name='SpotOperation',
        ),
        migrations.CreateModel(
            name='SpotTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_price', models.FloatField()),
                ('share', models.FloatField()),
                ('is_triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('signal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='trader.spotsignal')),
            ],
        ),
        migrations.CreateModel(
            name='SpotStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.FloatField()),
                ('share', models.FloatField()),
                ('is_triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('signal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='trader.spotsignal')),
            ],
        ),
    ]
