# Generated by Django 3.2.3 on 2021-08-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0010_auto_20210811_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotposition',
            old_name='volume',
            new_name='size',
        ),
        migrations.AddField(
            model_name='spotsignal',
            name='step_share_set_mode',
            field=models.CharField(default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='spotsignal',
            name='target_share_set_mode',
            field=models.CharField(default='manual', max_length=50),
        ),
    ]
