# Generated by Django 3.2.3 on 2021-08-11 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0012_auto_20210811_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotoperation',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='trader.spotposition'),
        ),
        migrations.AlterField(
            model_name='spotposition',
            name='signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='trader.spotsignal'),
        ),
        migrations.AlterField(
            model_name='spotstep',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='trader.spotsignal'),
        ),
        migrations.AlterField(
            model_name='spottarget',
            name='share',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spottarget',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='trader.spotsignal'),
        ),
    ]
