# Generated by Django 3.2.3 on 2021-08-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0013_auto_20210811_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotstep',
            name='amount_in_quote',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spottarget',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
