# Generated by Django 3.2.3 on 2021-08-19 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0014_auto_20210811_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotoperation',
            name='position',
        ),
        migrations.AddField(
            model_name='spotstep',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='spotstep',
            name='operation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step', to='trader.spotoperation'),
        ),
        migrations.AddField(
            model_name='spottarget',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='spottarget',
            name='operation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target', to='trader.spotoperation'),
        ),
    ]
