# Generated by Django 3.2.3 on 2021-08-19 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0017_alter_spotoperation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotoperation',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='trader.spotposition'),
        ),
    ]
