# Generated by Django 3.2.3 on 2021-08-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0019_alter_spotoperation_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotstep',
            old_name='cost',
            new_name='purchased_amount',
        ),
        migrations.RenameField(
            model_name='spottarget',
            old_name='cost',
            new_name='released_amount_in_quote',
        ),
    ]
