# Generated by Django 3.2.3 on 2021-08-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0020_auto_20210819_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotbot',
            name='status',
            field=models.CharField(default='running', max_length=50),
        ),
    ]
