# Generated by Django 3.2.3 on 2021-08-23 12:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0021_spotbot_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotStoploss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_price', models.FloatField()),
                ('is_triggered', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0)),
                ('released_amount_in_quote', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('operation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stoploss', to='trader.spotoperation')),
            ],
        ),
        migrations.AlterField(
            model_name='spotsignal',
            name='stoploss',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signal', to='trader.spotstoploss'),
        ),
    ]
