# Generated by Django 3.2.3 on 2021-08-23 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0022_auto_20210823_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotsignal',
            name='stoploss',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal', to='trader.spotstoploss'),
        ),
    ]
