# Generated by Django 3.2.3 on 2021-08-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0023_alter_spotsignal_stoploss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotsignal',
            name='step_share_set_mode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='spotsignal',
            name='target_share_set_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
