# Generated by Django 3.2.3 on 2021-08-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0024_auto_20210824_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotstoploss',
            name='is_trailed',
            field=models.BooleanField(default=False),
        ),
    ]
