# Generated by Django 3.2.3 on 2021-08-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0025_spotstoploss_is_trailed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotoperation',
            name='executed_at',
        ),
    ]
