# Generated by Django 3.2.3 on 2021-08-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0026_remove_spotoperation_executed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotorder',
            name='pure_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
