# Generated by Django 3.2.3 on 2021-08-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0027_spotorder_pure_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotposition',
            name='keep_open',
            field=models.BooleanField(default=False),
        ),
    ]
