# Generated by Django 3.2.3 on 2021-09-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0002_auto_20210903_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuresstep',
            name='margin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
