# Generated by Django 3.2.3 on 2021-09-07 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0003_alter_futuresstep_margin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuresstep',
            name='purchased_value',
        ),
    ]
