# Generated by Django 3.2.3 on 2021-09-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0005_alter_futuresposition_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuresbot',
            name='total_pnl',
        ),
        migrations.RemoveField(
            model_name='futuresbot',
            name='total_pnl_percentage',
        ),
        migrations.AddField(
            model_name='futuresbot',
            name='final_pnl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='futuresbot',
            name='final_pnl_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
