# Generated by Django 3.2.3 on 2021-09-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0006_auto_20210907_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuresorder',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='futuresorder',
            name='datetime',
        ),
    ]
