# Generated by Django 3.2.3 on 2021-09-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0008_remove_futuresorder_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuresstoploss',
            name='released_margin',
        ),
        migrations.RemoveField(
            model_name='futuresstoploss',
            name='size',
        ),
        migrations.AddField(
            model_name='futuresposition',
            name='released_margin',
            field=models.FloatField(default=0),
        ),
    ]
