# Generated by Django 3.2.7 on 2021-09-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0010_auto_20210910_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuresstep',
            name='created_at',
        ),
    ]
