# Generated by Django 3.2.7 on 2021-09-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0011_remove_futuresstep_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futuresposition',
            old_name='size',
            new_name='purchased_size',
        ),
    ]
