# Generated by Django 3.2.7 on 2021-09-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0012_rename_size_futuresposition_purchased_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futuresstep',
            old_name='size',
            new_name='purchased_size',
        ),
    ]
