# Generated by Django 3.2.7 on 2021-09-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0015_rename_purchased_size_futuresposition_holding_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurestarget',
            name='holding_size',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='futurestarget',
            name='share',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='futurestarget',
            name='type',
            field=models.CharField(choices=[('tp', 'Tp'), ('trail', 'Trail'), ('trail_and_tp', 'Trail And Tp')], default='tp', max_length=20),
            preserve_default=False,
        ),
    ]
