# Generated by Django 3.2.7 on 2021-09-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0016_auto_20210922_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurestarget',
            name='share',
            field=models.FloatField(default=0),
        ),
    ]
