# Generated by Django 3.2.7 on 2021-09-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0018_alter_futurestarget_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futurestarget',
            name='type',
        ),
    ]
