# Generated by Django 3.2.7 on 2021-09-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0019_remove_futurestarget_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futuressignal',
            old_name='step_share_set_mode',
            new_name='setup_mode',
        ),
    ]
