# Generated by Django 3.2.7 on 2021-09-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0020_rename_step_share_set_mode_futuressignal_setup_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresstep',
            name='leverage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
