# Generated by Django 3.2.7 on 2021-09-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0021_futuresstep_leverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuresstep',
            name='leverage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
