# Generated by Django 3.2.7 on 2021-09-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0022_alter_futuresstep_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresposition',
            name='is_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='futuresstep',
            name='is_market',
            field=models.BooleanField(default=False),
        ),
    ]
