# Generated by Django 3.2.7 on 2021-11-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0025_alter_futuresposition_leverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuresposition',
            name='leverage',
            field=models.IntegerField(),
        ),
    ]
