# Generated by Django 3.2.7 on 2021-12-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0030_futuressignal_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuressignal',
            name='source',
            field=models.CharField(default='manual', max_length=30),
        ),
    ]
