# Generated by Django 3.2.12 on 2022-02-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0031_futuressignal_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresposition',
            name='order_type',
            field=models.CharField(default='market', max_length=100),
        ),
    ]
