# Generated by Django 3.2.12 on 2022-08-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0032_futuresposition_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresbot',
            name='stopped_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='futuresstep',
            name='triggered_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='futuresstoploss',
            name='triggered_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='futurestarget',
            name='triggered_at',
            field=models.DateTimeField(null=True),
        ),
    ]
