# Generated by Django 3.2.12 on 2022-08-07 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0033_auto_20220803_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresstoploss',
            name='operation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stoploss', to='futures_trader.futuresoperation'),
        ),
        migrations.AlterField(
            model_name='futuresbot',
            name='status',
            field=models.CharField(default='created', max_length=50),
        ),
    ]
