# Generated by Django 3.2.12 on 2022-08-17 15:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0034_auto_20220807_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuressignal',
            name='confirmations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='futuressignal',
            name='leverage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='futuressignal',
            name='setup_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
