# Generated by Django 3.2.12 on 2022-08-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0035_auto_20220817_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuressignal',
            name='status',
            field=models.CharField(default='rejected', max_length=10),
        ),
    ]
