# Generated by Django 3.2.12 on 2022-08-17 16:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0036_futuressignal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuressignal',
            name='confirmations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
    ]
