# Generated by Django 3.2.12 on 2022-08-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0037_alter_futuressignal_confirmations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuressignal',
            name='status',
            field=models.CharField(default='waiting', max_length=10),
        ),
    ]
