# Generated by Django 3.2.12 on 2022-08-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0038_alter_futuressignal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuresposition',
            name='order_type',
        ),
    ]
