# Generated by Django 3.2.12 on 2022-10-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0039_remove_futuresposition_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesFlatResistanceTradeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
                ('point1_stoploss', models.FloatField()),
                ('point1_datetime', models.DateTimeField()),
                ('point1_price', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuturesFlatSupportTradeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
                ('point1_stoploss', models.FloatField()),
                ('point1_datetime', models.DateTimeField()),
                ('point1_price', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuturesInclineResistanceTradeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
                ('point1_stoploss', models.FloatField()),
                ('point1_datetime', models.DateTimeField()),
                ('point1_price', models.FloatField()),
                ('point2_datetime', models.DateTimeField()),
                ('point2_price', models.FloatField()),
                ('slope', models.FloatField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuturesInclineSupportTradeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
                ('point1_stoploss', models.FloatField()),
                ('point1_datetime', models.DateTimeField()),
                ('point1_price', models.FloatField()),
                ('point2_datetime', models.DateTimeField()),
                ('point2_price', models.FloatField()),
                ('slope', models.FloatField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
