# Generated by Django 3.2.12 on 2022-10-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0040_futuresflatresistancetradezone_futuresflatsupporttradezone_futuresinclineresistancetradezone_futures'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresflatresistancetradezone',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='futuresflatsupporttradezone',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='futuresinclineresistancetradezone',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='futuresinclinesupporttradezone',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
