# Generated by Django 3.2.12 on 2022-10-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0042_auto_20221027_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuresflatresistancetradezone',
            name='point1_stoploss',
        ),
        migrations.RemoveField(
            model_name='futuresflatsupporttradezone',
            name='point1_stoploss',
        ),
        migrations.RemoveField(
            model_name='futuresinclineresistancetradezone',
            name='point1_stoploss',
        ),
        migrations.RemoveField(
            model_name='futuresinclinesupporttradezone',
            name='point1_stoploss',
        ),
    ]
