# Generated by Django 3.2.12 on 2022-11-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures_trader', '0043_auto_20221030_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuressignal',
            name='triggered_at',
            field=models.DateTimeField(null=True),
        ),
    ]
